import type {
  LowStockItemPreview,
  ProjectItemPreview,
  ProjectPreview,
  ProjectTypeOption,
  SuggestedItemPreview,
} from '~/types/inventory'

const projectTypes: ProjectTypeOption[] = [
  {
    id: 'general-crafting',
    label: 'Crafting',
    description: 'Mixed supplies, tools, packaging, and workshop materials.',
  },
  {
    id: 'knitting',
    label: 'Knitting',
    description: 'Yarn, notions, needles, and blocking supplies.',
  },
  {
    id: 'crochet',
    label: 'Crochet',
    description: 'Yarn, hooks, stuffing, and markers for hook-based projects.',
  },
  {
    id: 'cardmaking',
    label: 'Card Making',
    description: 'Paper, embellishments, inks, and adhesive.',
  },
  {
    id: 'jewelry',
    label: 'Jewelry',
    description: 'Findings, beads, pliers, wire, and clasps.',
  },
  {
    id: 'sewing',
    label: 'Sewing',
    description: 'Fabric, patterns, thread, pins, and interfacing.',
  },
  {
    id: 'embroidery',
    label: 'Embroidery',
    description: 'Floss, hoops, fabric, and stabilizers for stitched work.',
  },
  {
    id: 'painting',
    label: 'Painting & Mixed Media',
    description: 'Paints, surfaces, brushes, mediums, and finishing supplies.',
  },
]

const projects: ProjectPreview[] = [
  {
    id: 'weekend-crafts',
    name: 'Weekend Craft Table',
    typeId: 'general-crafting',
    typeLabel: 'Crafting',
    summary: 'Shared odds-and-ends inventory for mixed-material gift projects and workshop prep.',
    memberCount: 2,
    itemCount: 6,
    lowStockCount: 1,
    lastUpdated: 'Updated 4 hours ago',
    tags: ['mixed-media', 'gift', 'packaging'],
  },
  {
    id: 'winter-scarves',
    name: 'Winter Scarves',
    typeId: 'knitting',
    typeLabel: 'Knitting',
    summary: 'Track yarn weight, needle sizes, and gift batches for cold-weather projects.',
    memberCount: 3,
    itemCount: 8,
    lowStockCount: 2,
    lastUpdated: 'Updated 2 hours ago',
    tags: ['gift', 'wool', 'holiday'],
  },
  {
    id: 'spring-cards',
    name: 'Spring Cards',
    typeId: 'cardmaking',
    typeLabel: 'Card Making',
    summary: 'Paper inventory for floral card kits, embellishments, and adhesive refills.',
    memberCount: 2,
    itemCount: 11,
    lowStockCount: 1,
    lastUpdated: 'Updated yesterday',
    tags: ['paper', 'floral', 'mail'],
  },
  {
    id: 'market-earrings',
    name: 'Market Earrings',
    typeId: 'jewelry',
    typeLabel: 'Jewelry',
    summary: 'Materials for fair inventory, color variants, and packaging supplies.',
    memberCount: 4,
    itemCount: 13,
    lowStockCount: 3,
    lastUpdated: 'Updated 3 days ago',
    tags: ['beads', 'findings', 'market'],
  },
]

const projectItemsByProjectId: Record<string, ProjectItemPreview[]> = {
  'weekend-crafts': [
    {
      id: 'craft-glue',
      name: 'Craft Glue',
      quantity: 4,
      unit: 'bottles',
      threshold: 2,
      location: 'Craft Cart',
      vendor: 'Maker Supply',
      cost: '$7.00',
      notes: 'Keep one bottle sealed for workshop kits.',
      photo: null,
      tags: ['adhesive', 'mixed-media'],
      isLowStock: false,
    },
    {
      id: 'kraft-tags',
      name: 'Kraft Gift Tags',
      quantity: 2,
      unit: 'packs',
      threshold: 3,
      location: 'Packaging Bin',
      vendor: 'Paper House',
      cost: '$5.00',
      notes: 'Used for market packaging and sample bundles.',
      photo: null,
      tags: ['packaging', 'gift'],
      isLowStock: true,
    },
  ],
  'winter-scarves': [
    {
      id: 'merino-yarn',
      name: 'Merino Wool Yarn',
      quantity: 3,
      unit: 'skeins',
      threshold: 5,
      location: 'Closet Bin A',
      vendor: 'Fiber Loft',
      cost: '$18.00',
      notes: 'Deep teal used in the scarf pattern sample.',
      photo: null,
      tags: ['wool', 'gift'],
      isLowStock: true,
    },
    {
      id: 'circular-needles',
      name: '5mm Circular Needles',
      quantity: 6,
      unit: 'pairs',
      threshold: 2,
      location: 'Tool Drawer',
      vendor: 'Maker Co.',
      cost: '$12.00',
      notes: 'Keep one pair in the travel kit.',
      photo: null,
      tags: ['tools'],
      isLowStock: false,
    },
    {
      id: 'stitch-markers',
      name: 'Stitch Markers',
      quantity: 8,
      unit: 'packs',
      threshold: 3,
      location: 'Closet Bin A',
      vendor: 'Fiber Loft',
      cost: '$6.00',
      notes: 'Use contrast colors for teaching sets.',
      photo: null,
      tags: ['notions'],
      isLowStock: false,
    },
  ],
  'spring-cards': [
    {
      id: 'a2-envelopes',
      name: 'A2 Envelopes',
      quantity: 12,
      unit: 'packs',
      threshold: 10,
      location: 'Paper Shelf',
      vendor: 'Card Studio',
      cost: '$9.00',
      notes: 'White and kraft assortments.',
      photo: null,
      tags: ['mail'],
      isLowStock: false,
    },
    {
      id: 'foam-adhesive',
      name: 'Foam Adhesive Squares',
      quantity: 2,
      unit: 'packs',
      threshold: 4,
      location: 'Paper Shelf',
      vendor: 'Craft Depot',
      cost: '$5.00',
      notes: 'Needed for layered flower cards.',
      photo: null,
      tags: ['adhesive'],
      isLowStock: true,
    },
  ],
  'market-earrings': [
    {
      id: 'gold-hooks',
      name: 'Gold Ear Hooks',
      quantity: 18,
      unit: 'pairs',
      threshold: 24,
      location: 'Jewelry Drawer',
      vendor: 'Bead Market',
      cost: '$14.00',
      notes: 'Nickel free hooks for the weekend booth.',
      photo: null,
      tags: ['findings'],
      isLowStock: true,
    },
    {
      id: 'jump-rings',
      name: '6mm Jump Rings',
      quantity: 40,
      unit: 'pieces',
      threshold: 30,
      location: 'Jewelry Drawer',
      vendor: 'Bead Market',
      cost: '$4.00',
      notes: 'Restock silver before gold.',
      photo: null,
      tags: ['findings'],
      isLowStock: false,
    },
    {
      id: 'display-cards',
      name: 'Display Cards',
      quantity: 9,
      unit: 'packs',
      threshold: 10,
      location: 'Packaging Crate',
      vendor: 'Print Supply House',
      cost: '$11.00',
      notes: 'Use matte cards for spring collection photos.',
      photo: null,
      tags: ['packaging'],
      isLowStock: true,
    },
  ],
}

const lowStockItems: LowStockItemPreview[] = [
  {
    id: 'kraft-tags',
    projectId: 'weekend-crafts',
    projectName: 'Weekend Craft Table',
    name: 'Kraft Gift Tags',
    quantity: 2,
    unit: 'packs',
    threshold: 3,
    location: 'Packaging Bin',
    tags: ['packaging', 'gift'],
  },
  {
    id: 'merino-yarn',
    projectId: 'winter-scarves',
    projectName: 'Winter Scarves',
    name: 'Merino Wool Yarn',
    quantity: 3,
    unit: 'skeins',
    threshold: 5,
    location: 'Closet Bin A',
    tags: ['wool', 'gift'],
  },
  {
    id: 'foam-adhesive',
    projectId: 'spring-cards',
    projectName: 'Spring Cards',
    name: 'Foam Adhesive Squares',
    quantity: 2,
    unit: 'packs',
    threshold: 4,
    location: 'Paper Shelf',
    tags: ['adhesive'],
  },
  {
    id: 'display-cards',
    projectId: 'market-earrings',
    projectName: 'Market Earrings',
    name: 'Display Cards',
    quantity: 9,
    unit: 'packs',
    threshold: 10,
    location: 'Packaging Crate',
    tags: ['packaging'],
  },
]

const suggestions: SuggestedItemPreview[] = [
  { id: 'suggest-glue', projectTypeId: 'general-crafting', name: 'Craft Glue', defaultUnit: 'bottles', tags: ['adhesive'] },
  { id: 'suggest-packaging', projectTypeId: 'general-crafting', name: 'Packaging', defaultUnit: 'packs', tags: ['packaging'] },
  { id: 'suggest-yarn', projectTypeId: 'knitting', name: 'Yarn', defaultUnit: 'skeins', tags: ['wool', 'fiber'] },
  { id: 'suggest-needle', projectTypeId: 'knitting', name: 'Knitting Needles', defaultUnit: 'pairs', tags: ['tools'] },
  { id: 'suggest-hook', projectTypeId: 'crochet', name: 'Crochet Hooks', defaultUnit: 'sets', tags: ['tools'] },
  { id: 'suggest-stuffing', projectTypeId: 'crochet', name: 'Stuffing', defaultUnit: 'bags', tags: ['fiber'] },
  { id: 'suggest-paper', projectTypeId: 'cardmaking', name: 'Cardstock', defaultUnit: 'packs', tags: ['paper'] },
  { id: 'suggest-adhesive', projectTypeId: 'cardmaking', name: 'Adhesive', defaultUnit: 'packs', tags: ['adhesive'] },
  { id: 'suggest-wire', projectTypeId: 'jewelry', name: 'Jewelry Wire', defaultUnit: 'spools', tags: ['wire'] },
  { id: 'suggest-hooks', projectTypeId: 'jewelry', name: 'Ear Hooks', defaultUnit: 'pairs', tags: ['findings'] },
  { id: 'suggest-fabric', projectTypeId: 'sewing', name: 'Fabric', defaultUnit: 'yards', tags: ['fabric'] },
  { id: 'suggest-thread', projectTypeId: 'sewing', name: 'Thread', defaultUnit: 'spools', tags: ['thread'] },
  { id: 'suggest-floss', projectTypeId: 'embroidery', name: 'Embroidery Floss', defaultUnit: 'skeins', tags: ['thread'] },
  { id: 'suggest-hoop', projectTypeId: 'embroidery', name: 'Embroidery Hoops', defaultUnit: 'sets', tags: ['tools'] },
  { id: 'suggest-paint', projectTypeId: 'painting', name: 'Acrylic Paint', defaultUnit: 'bottles', tags: ['paint'] },
  { id: 'suggest-canvas', projectTypeId: 'painting', name: 'Canvas Panels', defaultUnit: 'packs', tags: ['surface'] },
]

export function useInventoryPreview() {
  const getProjectById = (projectId: string) => projects.find(project => project.id === projectId)

  const getProjectItemsByProjectId = (projectId: string) => projectItemsByProjectId[projectId] ?? []

  const getSuggestionsByProjectType = (projectTypeId: string) =>
    suggestions.filter(item => item.projectTypeId === projectTypeId)

  return {
    lowStockItems,
    projectTypes,
    projects,
    suggestions,
    getProjectById,
    getProjectItemsByProjectId,
    getSuggestionsByProjectType,
  }
}
